### ISSUE TITLE
quotation marks

### ISSUE THREAD

**Issue by ninadepina** [Whtneyas/web-app-from-scratch-2223#5]
you're using both of the quotations marks (`"` and `'`) in one file, I'd choose one and use it throughout the whole file

**Comment by Whtneyas** [comment]
Thanks!! Solved

**Comment by ninadepina** [comment]
you could also look into using a code formatter (e.g. Prettier), than this won't be a problem

**Comment by Whtneyas** [comment]
> you could also look into using a code formatter (e.g. Prettier), than this won't be a problem

I already have it installed but I have forgotten how it works. Do you maybe know the key for enabling it ?
