### ISSUE TITLE
optimising function

### ISSUE THREAD

**Issue by ninadepina** [Whtneyas/web-app-from-scratch-2223#9]
https://github.com/Whtneyas/web-app-from-scratch-2223/blob/c39ec7b634f4f570994c42de2c56c871021718c6/Bijbelversus/script.js/modules/displayBibleQuote.js#L3-L14

You can optimise this function by destructuring 'randomVerse', so you can directly access the properties instead of repeatedly referencing back to it. If you do, you need to rename the `const chapter` and `const verse` because those are also names go the properties. The optimised code would look something like this:
```javascript
const displayBibleQuote = ({ book_name, chapter, verse, text }) => {
	const nameBook = document.querySelector('h2'); // selects h2 which is the name of the book
	const numChapter = document.querySelector('h3'); // selects h3 which is the chapter
	const numVerse = document.querySelector('span'); //selects the number of the verse
	const textVerse = document.querySelector('p'); // selects the p that contains the verse

	nameBook.textContent = book_name;
	numChapter.textContent = chapter;
	numVerse.textContent = verse;
	textVerse.textContent = text;
};
```

**Comment by Whtneyas** [comment]
Thanks Nina.
